CREATE TABLE [dbo].[Andar](
	[IDAndar] [int] IDENTITY(1,1) NOT NULL,
	[Andar] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[IDAndar] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Andar] ON 
GO
INSERT [dbo].[Andar] ([IDAndar], [Andar]) VALUES (1, 1)
GO
INSERT [dbo].[Andar] ([IDAndar], [Andar]) VALUES (2, 2)
GO
SET IDENTITY_INSERT [dbo].[Andar] OFF
GO
