CREATE TABLE [dbo].[STATUS](
	[IDStatus] [int] IDENTITY(1,1) NOT NULL,
	[Descricao] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDStatus] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[STATUS] ON 
GO
INSERT [dbo].[STATUS] ([IDStatus], [Descricao]) VALUES (1, N'Aberto')
GO
INSERT [dbo].[STATUS] ([IDStatus], [Descricao]) VALUES (2, N'Trancado')
GO
INSERT [dbo].[STATUS] ([IDStatus], [Descricao]) VALUES (3, N'Interditado')
GO
SET IDENTITY_INSERT [dbo].[STATUS] OFF
GO
